# Tabuada
numero = input('Digite um número para ver sua tabuada: ')
numero_int = int(numero)
print('---------------------------------------')
print(f'{numero_int} x  {0} = {numero_int * 0}')
print(f'{numero_int} x  {1} = {numero_int * 1}')
print(f'{numero_int} x  {2} = {numero_int * 2}')
print(f'{numero_int} x  {3} = {numero_int * 3}')
print(f'{numero_int} x  {4} = {numero_int * 4}')
print(f'{numero_int} x  {5} = {numero_int * 5}')
print(f'{numero_int} x  {6} = {numero_int * 6}')
print(f'{numero_int} x  {7} = {numero_int * 7}')
print(f'{numero_int} x  {8} = {numero_int * 8}')
print(f'{numero_int} x  {9} = {numero_int * 9}')
print(f'{numero_int} x {10} = {numero_int * 10}')
print('---------------------------------------')